# This prj.conf borrowed from Iomico Zephyr Int' lecture 4, demo 2

CONFIG_LOG=y
CONFIG_ZBUS=y
CONFIG_ZBUS_MSG_SUBSCRIBER=y
CONFIG_ZBUS_MSG_SUBSCRIBER_NET_BUF_POOL_SIZE=32
CONFIG_THREAD_NAME=y

# Hardware watchdog - last line of defence
CONFIG_WATCHDOG=y . . . Zephyr does not appear to support STM32F432KC watchdog

CONFIG_WDT_LOG_LEVEL_DBG=y

# Per-thread software watchdog.  Identifies which thread is stuck.
CONFIG_TASK_WDT=y
CONFIG_TASK_WDT_HW_FALLBACK=y
CONFIG_TASK_WDT_MIN_TIMEOUT=20

# Application (l5-task1) specific
CONFIG_SENSOR_READING_COUNT=20
CONFIG_PUBLISHER_PERIOD_MS=150
CONFIG_SUBSCRIBER_WDT_TIMEOUT_MS=300
CONFIG_SUBSCRIBER_SIMULATED_WORK_DELAY_MS=600
